cec.sh fails since tvservice is not supported w/ vc4-kms-v3d -> use fkms
```console
$ ./cec.sh on
...
ERROR:   [            1003]     RegisterLogicalAddress - CEC is being used by another application. Run "tvservice --off" and try again.
...
$ tvservice --off
tvservice is not supported when using the vc4-kms-v3d driver.
Similar features are available with standard linux tools
such as modetest from libdrm-tests.
```
Found via https://github.com/SvenVD/rpisurv/issues/143